version: "3"

services:
    mailpit:
        container_name: mailpit
        image: axllent/mailpit:latest
        ports:
            - "8025:8025" # Web UI
            - "1025:1025" # SMTP
        environment:
            - MP_SMTP_AUTH_ACCEPT_ANY=1
            - MP_SMTP_AUTH_ALLOW_INSECURE=1
        restart: unless-stopped

    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Bigs3cRet
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        volumes:
            - sqlserver_data:/var/opt/mssql
            - ./obj/dbinit/:/opt/dbinit/
        restart: unless-stopped

volumes:
    sqlserver_data:
